language: node_js

node_js:
  - '8.9.0'

branches:
  only:
  - /^master$/

cache:
  directories:
  - node_modules

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install

script:
  - npm run lint && npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)
