version: "2"
services:
  app:
    container_name: "kishanmundha/koa-ts"
    restart: always
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"